import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-green-50">
        <Navbar />
        <main className="py-16">
          <div className="border border-green-900 p-16 max-w-2xl mx-auto shadow-2xl">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
