
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."Author" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Author" OWNER TO "postgres";

ALTER TABLE "public"."Author" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Author_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Nothing1" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Nothing1" OWNER TO "postgres";

ALTER TABLE "public"."Nothing1" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Nothing1_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."TableX1" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."TableX1" OWNER TO "postgres";

ALTER TABLE "public"."TableX1" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TableX1_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."TableX2" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."TableX2" OWNER TO "postgres";

ALTER TABLE "public"."TableX2" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TableX2_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."TableX3" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."TableX3" OWNER TO "postgres";

ALTER TABLE "public"."TableX3" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TableX3_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."Author"
    ADD CONSTRAINT "Author_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Nothing1"
    ADD CONSTRAINT "Nothing1_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."TableX1"
    ADD CONSTRAINT "TableX1_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."TableX2"
    ADD CONSTRAINT "TableX2_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."TableX3"
    ADD CONSTRAINT "TableX3_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."Nothing1" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."TableX2" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."TableX3" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."Author" TO "anon";
GRANT ALL ON TABLE "public"."Author" TO "authenticated";
GRANT ALL ON TABLE "public"."Author" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Author_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Author_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Author_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Nothing1" TO "anon";
GRANT ALL ON TABLE "public"."Nothing1" TO "authenticated";
GRANT ALL ON TABLE "public"."Nothing1" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Nothing1_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Nothing1_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Nothing1_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."TableX1" TO "anon";
GRANT ALL ON TABLE "public"."TableX1" TO "authenticated";
GRANT ALL ON TABLE "public"."TableX1" TO "service_role";

GRANT ALL ON SEQUENCE "public"."TableX1_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TableX1_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TableX1_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."TableX2" TO "anon";
GRANT ALL ON TABLE "public"."TableX2" TO "authenticated";
GRANT ALL ON TABLE "public"."TableX2" TO "service_role";

GRANT ALL ON SEQUENCE "public"."TableX2_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TableX2_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TableX2_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."TableX3" TO "anon";
GRANT ALL ON TABLE "public"."TableX3" TO "authenticated";
GRANT ALL ON TABLE "public"."TableX3" TO "service_role";

GRANT ALL ON SEQUENCE "public"."TableX3_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TableX3_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TableX3_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
