on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        required: true
        type: string
      EXECUTION_COMMAND:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      EC2_USERNAME:
        required: true
      ECR_REGISTRY:
        required: true
      SSH_KEY:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      DATABASE_URL:
        required: true
      EC2_IP_ADDRESS:
        required: true
      ECR_REPOSITORY:
        required: true
      AWS_REGION:
        required: true
      NODE_ENV:
        required: true
      APP_PORT:
        required: true
        
env:
  HOSTNAME: ${{ secrets.EC2_IP_ADDRESS }}
  USER_NAME: ${{secrets.EC2_USERNAME}}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
jobs:
  test:
    name: Application deployment
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Prepare EC2 SSH credentials
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key;
          echo "ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}";
      - name: Login to ECR on EC2
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - name: Stop running app
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "docker stop ${ECR_REPOSITORY}-${NODE_ENV} || true"
      - name: Clean unused containers
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "docker system prune -f"
      - name: Clean unused images
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "docker image prune -af"
      - name: Start app
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APP_PORT: ${{ secrets.APP_PORT }}
          EXECUTION_COMMAND: ${{ inputs.EXECUTION_COMMAND }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
            docker run \
              --name ${ECR_REPOSITORY}-${NODE_ENV} \
              -e DATABASE_URL=${DATABASE_URL} \
              -e APP_PORT=${APP_PORT} \
              -p ${APP_PORT}:${APP_PORT} \
              -d $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
              $EXECUTION_COMMAND
          "



