version: "3"
services:
  # node-app:
  #   # replace username/repo:tag with your name and image details
  #   image: node-app:v1.0.0
  #   deploy:
  #     replicas: 5
  #     resources:
  #       limits:
  #         cpus: "0.1"
  #         memory: 50M
  #     restart_policy:
  #       condition: on-failure
  #   ports:
  #     - "4000:8081"
  #   networks:
  #     - webnet
  spring-app:
    # replace username/repo:tag with your name and image details
    image: spring-app:v1.0.0
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: