apiVersion: v1
kind: Service
metadata:
  name: myapp-lb
  annotations:
    kubernetes.digitalocean.com/firewall-managed: "false"
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
      protocol: TCP
  selector:
    app: myapp
  externalTrafficPolicy: Local