apiVersion: v1
kind: Pod
metadata:
  name: hello-world-sleep-readi-app
  labels:
    name: hello-world-sleep-readi-app
    app: hello-world-sleep-readi-app
spec:
  containers:
  - name: hello-world-sleep-readi-container
    image: franciscovilchezv/hello-world:sleep-0.0.1
    ports:
      - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
