apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-sleep-deployment
spec:
  selector:
    matchLabels:
      app: hello-world-sleep-app
  template:
    metadata:
      labels:
        app: hello-world-sleep-app
    spec:
      containers:
      - name: hello-world-sleep-container
        image: franciscovilchezv/hello-world:sleep-0.0.1
        ports:
        - containerPort: 80
  replicas: 1
