apiVersion: v1
kind: Service
metadata:
  name: hello-world-sleep-node-port
spec:
  type: NodePort
  selector:
    app: hello-world-sleep-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
