on: 
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      database-url:
        required: true

jobs:
  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test docker-compose
        env:
          DATABASE_URL: ${{ secrets.database-url }}
        run: docker-compose -f docker-compose-test.yml up --exit-code-from integration-test

